I103 redesign edit to be a modal in visit
codersforcauses/poops pull request #119
Opened 2022-07-30 04:38 UTC by Dustybluelight

## Change Summary
Change edit from a modal to add.
Added day names, changed display name to client name.
Changed end time to duration.
Client pets and clients drawn from contact list.

:+1: 

## Other Information
Done all the things in #111.

2022-11-29 09:20 UTC, dct0 commented
Should reusable button be integrated in this issue as well?

2022-11-29 09:33 UTC, scratchclaggy commented
> Should reusable button be integrated in this issue as well?
@dct0 
If you're happy to use it, you can merge `i63-reusable-button` into this branch and that should be ready to go (pending review). Otherwise, if this PR goes through before #132 then I'll swap out the buttons.

2022-12-14 10:50 UTC, skyheat requested changes
No glaring issues from what I can see.

Good work!

2022-12-14 10:50 UTC, skyheat commented on src/components/Visit/formfield.tsx
> +import React, { ChangeEvent } from 'react'
Importing react is unnecessary as next.js automatically imports it.

2022-12-14 14:14 UTC, scratchclaggy reviewed
Good stuff so far, I've left a few comments throughout each of the files.

Some additional things:

![image](https://user-images.githubusercontent.com/34858205/207616357-b004edd6-3306-40b1-83ce-269bb0f4bc8b.png)
Is it possible to not use the US date format with this date picker component?

2022-12-14 14:39 UTC, dct0 commented on src/components/Visit/utils.ts
> +    if (userDoc.contacts[i].id === id) {
Could grab the contact's info by the name instead?

2022-12-14 14:43 UTC, dct0 commented on public/sw.js.map
> +<<<<<<< HEAD
Looks like an old file that should be ignored in the .gitignore. Deleted.

2022-12-14 15:00 UTC, dct0 commented on src/pages/visit/set.tsx
> +                // event.target.value = event.target.value.substring(0, 16) // fixes invalid input on ios safari? can't test
Uncommented. Maybe someone with mobile safari can check this works?

2022-12-15 04:19 UTC, NicholasChoong commented on src/components/Visit/utils.ts
> +    if (userDoc.contacts[i].id === id) {
> @NicholasChoong I guess we need to keep the `id` field?

yea

2022-12-15 04:41 UTC, scratchclaggy commented on src/components/Visit/utils.ts
> +    if (userDoc.contacts[i].id === id) {
In the contacts page, we're finding contacts via index, so Nic and I were confused about why contacts needed an `id` as well. Is it possible to use the same technique here?

2022-12-15 04:49 UTC, dct0 commented on src/components/Visit/utils.ts
> +export const formatTimestamp = (timestamp?: Timestamp) => {
It seems like ` Intl.DateTimeFormat()` requires a specified locale. If none is specified, it does not add the time so I think `humanizeTimestamp()` is fine.
```js
const date = new Date(Date.UTC(2020, 11, 20, 3, 23, 16, 738));

console.log(new Intl.DateTimeFormat('en-AU', { dateStyle: 'long', timeStyle: 'medium', timeZone: 'Australia/Sydney' }).format(date));
// Output: "20 December 2020 at 2:23:16 pm"

console.log(new Intl.DateTimeFormat({ dateStyle: 'long', timeStyle: 'medium', timeZone: 'Australia/Sydney' }).format(date))
// Output: "20/12/2020" on my browser
```

2022-12-15 05:07 UTC, dct0 commented on src/pages/visit/set.tsx
> +      petNames: userDoc.contacts[findContactIndex(clientName, userDoc)].pets, // TODO?: find contact by id instead
Removed todos

2022-12-15 06:14 UTC, dct0 commented on src/pages/visit/set.tsx
> +      userDoc.visits[id] = data
I think I did it?

2022-12-15 06:15 UTC, dct0 commented on src/components/Visit/utils.ts
> +    if (userDoc.contacts[i].id === id) {
Removed the function.

2022-12-15 06:18 UTC, dct0 commented on src/components/Visit/utils.ts
> +import { Timestamp } from 'firebase/firestore'
Moved file to `src/utils/index.ts`

2022-12-15 07:34 UTC, skyheat approved these changes
Nice

2022-12-15 07:39 UTC, merged