I126 user card is missing in contact page
codersforcauses/poops pull request #144
Opened 2022-12-08 05:31 UTC by scratchclaggy

## Change Summary
Addresses #126 

This change introduces a new field to the Firestore `userDoc` called info.

![image](https://user-images.githubusercontent.com/34858205/206364015-38ea964c-f8d4-4114-b6e6-9875f3175d8f.png)

Essentially, the user's information is stored in an object called info that shares the same shape as a contact. In the contact list, an index is used to navigate to the detailed view / form for a given contact, so this change has modified the way the index is used in two ways:

- The index can now be `null`, this is true when no contact has been selected (i.e. the list view). Prievously the value `-1` was used for this state
- The value `-1` now refers to the the user's information, rather than one of their contacts

Additionally, a new callback was exposed from the Firestore context to allow updating of the user's info.

### Change Form

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
 
These changes will require a DB wipe / schema change.

# Related Issue

- Resolve #126

2022-12-09 15:33 UTC, skyheat reviewed
Looks good to me but I'm not too familiar with the firebase specifics. I'll let @NicholasChoong take a look at it.

2022-12-15 06:48 UTC, NicholasChoong commented on src/components/Contact/contactitem.tsx
> +          <p className='text-gray-500'>{truncateText(contact.pets, 16)}</p>
we can also truncate text with css
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

2022-12-15 06:52 UTC, NicholasChoong commented on src/context/ContactContext/index.tsx
> +        if (reg.test(contact.clientName) || reg.test(contact.pets!)) {
should we check if pets is not null first before passing it to another function?

2022-12-15 07:02 UTC, NicholasChoong requested changes
Great work

2022-12-15 07:02 UTC, NicholasChoong commented on src/pages/contact.tsx
>              <div className='border-grey m-2 flex flex-row rounded-xl border-2'>
maybe call the getters and store the values in some constants before the jsx to reduce the number of function calls

2022-12-17 06:44 UTC, NicholasChoong approved these changes
Good Work

2022-12-17 06:45 UTC, merged