I136 fix margin between save button and navbar in contactdetails page
codersforcauses/poops pull request #158
Opened 2022-12-17 07:16 UTC by ok7097269

## Change Summary
**[fix margin between save button and navbar in contactdetails page]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2022-12-20 07:21 UTC, skyheat commented on src/components/Contact/contactform.tsx
>            </div>
Looks like you have a formatting issue here. Make sure to run prettier :)

2022-12-20 07:22 UTC, skyheat requested changes
Looks good! Just a formatting issue.

2023-01-02 01:38 UTC, NicholasChoong reviewed
Why is there a submodule of the repo itself?

2023-01-08 07:51 UTC, skyheat approved these changes

2023-01-11 09:18 UTC, merged