WIP | #155 refactor firestore documents to use sub collections
codersforcauses/poops pull request #165
Opened 2022-12-22 08:11 UTC by scratchclaggy

## Change Summary

This PR represents major breaking changes, and the addition of two new JS libraries. The changes are:

- Remove the Firestore / Contact contexts
- Use [React Query](https://tanstack.com/query/v4/docs/react/overview) for all datafetching from Firestore
- Expose data fetching via hooks (see the `src/hooks` directory)
- Share state accross multiple components with [Jotai](https://jotai.org/docs/introduction)
- Change the user 'schema' in Firestore, so that visits and contacts are sub-collections, and each visit / contact is a separate document within their respective collection

### Change Form

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

2022-12-22 08:11 UTC, scratchclaggy commented
The WIP flag is so that I complete documentation before this is merged in.

2022-12-22 22:44 UTC, scratchclaggy commented
Documentation is now included in the README.

2022-12-27 11:22 UTC, NicholasChoong requested changes
Good work!! I read some of the documentations on Jotai and that they also have a library that integrates jotai into React Query. Surprise to see that Provider is optional in Jotai.

2022-12-27 11:22 UTC, NicholasChoong commented on src/hooks/user.ts
> +    visits: []
I dont think this array is needed

2022-12-29 03:09 UTC, scratchclaggy commented on src/types/types.ts
> +  visits: Visit[]
Yeps, that's correct, thanks for picking that up.

2022-12-29 10:34 UTC, NicholasChoong approved these changes
Good to merge

2022-12-29 12:02 UTC, merged