I206 User / contact updates not shown in UI
codersforcauses/poops pull request #207
Opened 2023-01-19 07:55 UTC by scratchclaggy

## Change Summary

This PR addresses #206 and brings a number of improvements. One of the reasons that the previous bug was present was due to the fact that the user was treated as a contact, and this required some workarounds. This PR refactors things so that the contacts page is split like so:

```bash
src/pages/contact
├── [id].tsx
├── index.tsx
└── new.tsx

0 directories, 3 files
```

Now, instead of using multiple pieces of client side state (via Jotai) we can navigate to the profile page for the user and to contacts with dynamic page routes. Additionally, this also gives the ability to show the most newly created contact when adding a new contact, instead of redirecting to the contact list like before.

### Change Form
- [X] The pull request title has an issue number
- [X] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

2023-01-21 07:51 UTC, scratchclaggy commented
TODO:

- New contact needs a back button
- Use page navigation for edit vs detail view

2023-01-30 11:16 UTC, dct0 commented
> * New contact needs a back button

In #222 I have made the cancel button present for both editing and adding a new contact. Having the 'back' button at the bottom of the page and requiring scrolling is not good design. Couldn't find a nice way to have the button at the top so maybe this could be made into a separate issue?

2023-02-02 08:03 UTC, scratchclaggy commented
Should be ready for review now

2023-02-02 13:07 UTC, dct0 commented on firebase/functions/package.json
> +    "jest": "28.0.0"
Should we keep this?

2023-02-02 13:20 UTC, dct0 commented on src/components/Contact/contactform.tsx
> +          </Button>
The default type for buttons is 'submit' so hitting cancel submits the form.

2023-02-02 13:28 UTC, dct0 requested changes
Good stuff! Just some small changes to make.

2023-02-03 03:24 UTC, scratchclaggy commented on src/pages/contact/[id]/edit.tsx
> +    </div>
Yeah good idea, I've added it now.

2023-02-04 03:06 UTC, dct0 approved these changes
All good

2023-02-04 03:07 UTC, merged