I215 remember the values of last visits for each clients in the visit form
codersforcauses/poops pull request #220
Opened 2023-01-24 11:44 UTC by dct0

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
- Visits are now ordered by latest start time
- Default visit type is `walk`
- When a client name is selected, all fields are prefilled with the most recent visit for the selected client (excluding `visitType`, `startTime` and `notes`

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [X] The pull request title has an issue number
- [X] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
- Should visits instead be sorted by the last updated time of the visit?

2023-01-27 15:52 UTC, skyheat commented on src/pages/visit/[id]/index.tsx
> +    )
Probs best to remove comments, feel like this is pretty self explanatory

2023-01-27 15:54 UTC, skyheat requested changes
Looks good to me otherwise! Thanks for picking up this `difficulty::hard` and `point::5` issue kings 👑

2023-01-27 23:47 UTC, justinliangg commented
> Looks good to me otherwise! Thanks for picking up this `difficulty::hard` and `point::5` issue kings 👑
😂 No problem! Thanks for the review :)

2023-01-28 03:27 UTC, skyheat approved these changes
ez

2023-01-28 03:27 UTC, merged