93 2 step new
codersforcauses/poops pull request #227
Opened 2023-01-28 07:38 UTC by Wolfgang1208

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
1, Created a form for new users to fill in details
2, Redirect if users' doc on firestore having any null values in name, email, phone.

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2023-01-28 11:14 UTC, skyheat commented
![396B5272-3948-4E83-A279-20EF61F6E486](https://user-images.githubusercontent.com/6574274/215263536-88fe2682-e933-4cf0-88ab-45fc63d09ff5.png)

page is bugged on phone

2023-02-01 15:40 UTC, skyheat requested changes
Looks great otherwise! Good job 🥇

2023-02-01 17:51 UTC, Wolfgang1208 commented on src/pages/signupDetails.tsx
> +// import LoginPanel from '@/components/Login/LoginPanel'
The image is used for poops logo

2023-02-01 17:55 UTC, Wolfgang1208 commented on src/components/UpdateDetails/UpdateDetailsPanel.tsx
> +// TODO add correct redirect to the pages path // done
yes

2023-02-01 17:55 UTC, Wolfgang1208 commented on src/components/UpdateDetails/UpdateDetailsPanel.tsx
> +      setErr(true) // debug only
removed

2023-02-01 17:55 UTC, Wolfgang1208 commented on src/components/UpdateDetails/UpdateDetailsPanel.tsx
> +            // console.log(error)
removed

2023-02-01 17:55 UTC, Wolfgang1208 commented on src/components/UpdateDetails/UpdateDetailsPanel.tsx
> +      setErr(false) // debug only
removed

2023-02-01 17:55 UTC, Wolfgang1208 commented on src/components/UpdateDetails/UpdateDetailsPanel.tsx
> +  // push test
removed

2023-02-01 18:00 UTC, Wolfgang1208 commented
request changes done

2023-02-01 18:01 UTC, Wolfgang1208 commented
Checked 2-step login in code works well after applied Jun's changes.

2023-02-02 04:05 UTC, skyheat commented on src/pages/signupDetails.tsx
> +// import LoginPanel from '@/components/Login/LoginPanel'
I accidently selected lines 2-4, should only be removing line 5

2023-02-02 04:05 UTC, skyheat approved these changes

2023-02-02 05:45 UTC, merged