I230 move sendemail next api to the frontend
codersforcauses/poops pull request #286
Opened 2023-03-01 09:46 UTC by NicholasChoong

## Change Summary
- Updated doc
- email trigger is now fully working

2023-03-01 10:45 UTC, scratchclaggy commented on docs/functions.md
> +```nash
Is this a typo? Never heard of nash.

2023-03-01 10:50 UTC, scratchclaggy requested changes
Haven't tested the behaviour yet, but code looks fine to me.

2023-03-01 10:50 UTC, scratchclaggy commented on src/components/Visit/VetForm/index.tsx
> +      await Promise.all([mutateVetConcerns(data), sendEmail(message)])
`mutateVetConcerns()` isn't `async`

2023-03-04 18:01 UTC, NicholasChoong commented on docs/functions.md
> +```nash
def a type

2023-03-06 10:34 UTC, scratchclaggy approved these changes
Looks good :rocket:

2023-03-08 03:15 UTC, merged